# Generated by Django 3.2.8 on 2021-10-16 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alvo',
            fields=[
                ('identificador', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Alvo')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('data_expiracao', models.DateField(null=True, verbose_name='Data da Expiracao')),
            ],
        ),
    ]
