# Generated by Django 3.2.8 on 2021-10-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alvo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alvo',
            name='data_expiracao',
            field=models.DateField(help_text='formato: YYYY-MM-DD', null=True, verbose_name='Data da Expiracao'),
        ),
    ]
